name: CI - Testes Automatizados

on:
  push:
    branches:
      - main

  workflow_dispatch:

  schedule:
    - cron: '0 12 * * *'

jobs:
  teste:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar dependências
        run: npm install

      - name: Executar testes e gerar relatório
        run: npx mocha --reporter json > relatorio-testes.json

      - name: Upload do relatório
        uses: actions/upload-artifact@v4
        with:
          name: relatorio-testes
          path: relatorio-testes.json
